laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('o-que-fazemos', 'OQueFazemosController@index')->name('o-que-fazemos');
    Route::get('portfolio/{categoria_slug?}', 'PortfolioController@index')->name('portfolio');
    Route::get('sobre-nos/{pagina_slug?}', 'SobreNosController@index')->name('sobre-nos');
    Route::get('espaco-talenco/{blog_categoria_slug?}', 'BlogController@index')->name('blog');
    Route::get('espaco-talenco/{blog_categoria_slug}/{post_slug}', 'BlogController@show')->name('blog.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('sobre-nos-bg', 'SobreNosBgController', ['only' => ['index', 'update']]);
        Route::resource('blog/categorias', 'BlogCategoriasController', ['parameters' => ['categorias' => 'categorias_blog']]);
		Route::resource('blog', 'BlogController');
		Route::resource('depoimentos', 'DepoimentosController');
		Route::resource('banners', 'BannersController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('o-que-fazemos', 'OQueFazemosController', ['only' => ['index', 'update']]);
		Route::resource('portfolio/categorias', 'PortfolioCategoriasController', ['parameters' => ['categorias' => 'categorias_portfolio']]);
		Route::resource('portfolio', 'PortfolioController');
		Route::get('portfolio/{portfolio}/imagens/clear', [
			'as'   => 'painel.portfolio.imagens.clear',
			'uses' => 'PortfolioImagensController@clear'
		]);
		Route::resource('portfolio.imagens', 'PortfolioImagensController', ['parameters' => ['imagens' => 'imagens_portfolio']]);
		Route::resource('sobre-nos.topicos', 'SobreNosTopicosController');
		Route::resource('sobre-nos', 'SobreNosController');
		Route::resource('unidades', 'UnidadesController');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('newsletter', 'NewsletterController', ['only' => ['index', 'destroy']]);
        Route::get('newsletter/exportar', 'NewsletterController@exportar')->name('painel.newsletter.exportar');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/PortfolioController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\PortfolioRequest;
use App\Http\Controllers\Controller;

use App\Models\Projeto;
use App\Models\ProjetoCategoria;

class PortfolioController extends Controller
{
    private $categorias;

    public function __construct()
    {
        $this->categorias = ProjetoCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (ProjetoCategoria::find($filtro)) {
            $registros = Projeto::where('portfolio_categoria_id', $filtro)->ordenados()->get();
        } else {
            $registros = Projeto::leftJoin('portfolio_categorias as cat', 'cat.id', '=', 'portfolio_categoria_id')
                ->orderBy('cat.ordem', 'ASC')
                ->orderBy('cat.id', 'DESC')
                ->select('portfolio.*')
                ->ordenados()->get();
        }

        return view('painel.portfolio.index', compact('categorias', 'registros', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.portfolio.create', compact('categorias'));
    }

    public function store(PortfolioRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Projeto::upload_capa();

            Projeto::create($input);

            return redirect()->route('painel.portfolio.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Projeto $registro)
    {
        $categorias = $this->categorias;

        return view('painel.portfolio.edit', compact('registro', 'categorias'));
    }

    public function update(PortfolioRequest $request, Projeto $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Projeto::upload_capa();

            $registro->update($input);

            return redirect()->route('painel.portfolio.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Projeto $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.portfolio.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Models\ProjetoCategoria;

class PortfolioController extends Controller
{
    public function index(ProjetoCategoria $categoria)
    {
        $categorias = ProjetoCategoria::ordenados()->get();

        if (! $categorias->count()) {
            abort('404');
        }

        if (! $categoria->exists) {
            $categoria = $categorias->first();
        }

        return view('frontend.portfolio', compact('categorias', 'categoria'));
    }
}

laravel/resources/views/painel/portfolio/categorias/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Portfólio /</small> Adicionar Categoria</h2>
    </legend>

    {!! Form::open(['route' => 'painel.portfolio.categorias.store']) !!}

        @include('painel.portfolio.categorias.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/portfolio/categorias/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Portfólio /</small> Editar Categoria</h2>
    </legend>

    {!! Form::model($categoria, [
        'route'  => ['painel.portfolio.categorias.update', $categoria->id],
        'method' => 'patch'])
    !!}

    @include('painel.portfolio.categorias.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/portfolio/categorias/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('subtitulo', 'Subtítulo (opcional)') !!}
    {!! Form::text('subtitulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.portfolio.categorias.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/portfolio/categorias/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.portfolio.index') }}" title="Voltar para Portfólio" class="btn btn-sm btn-default">
        &larr; Voltar para Portfólio    </a>

    <legend>
        <h2>
            <small>Portfólio /</small> Categorias

            <a href="{{ route('painel.portfolio.categorias.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Categoria</a>
        </h2>
    </legend>

    @if(!count($categorias))
    <div class="alert alert-warning" role="alert">Nenhuma categoria cadastrada.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="portfolio_categorias">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($categorias as $categoria)
            <tr class="tr-row" id="{{ $categoria->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>
                    @if($categoria->subtitulo)
                    <small>{{ $categoria->subtitulo }}</small><br>
                    @endif
                    {{ $categoria->titulo }}
                </td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.portfolio.categorias.destroy', $categoria->id), 'method' => 'delete')) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.portfolio.categorias.edit', $categoria->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection